### +proj=laea +lat_0=36.0 +lon_0=104.0 +ellps=WGS84
# [5, 55, 70, 140] 重新生成
# python coord2area_def.py china_4km_eqc eqc 5, 55, 70, 140
china_4km:
  description: china_4km
  projection:
    proj: laea
    ellps: WGS84
    lat_0: 36.0
    lon_0: 104.0
  shape:
    height: 967
    width: 1628
  area_extent:
    lower_left_xy: [-3256286.769420, -1516788.718383]
    upper_right_xy: [3256286.769420, 2351366.332281]


china_4km_eqc:
  description: china_4km_eqc
  projection:
    proj: eqc
    ellps: WGS84
    lat_0: 36.0
    lon_0: 104.0
  shape:
    height: 1002
    width: 1725
  area_extent:
    lower_left_xy: [-3450904.214591, -2003750.834279]
    upper_right_xy: [3450904.214591, 2003750.834279]